### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by julioflima** [juloko/my-video#1]
- [x] **Escopo do projeto**
---
- [ ] **Orquestrador**
  - [x] Montar interface web;
  - [x] Perguntar termo de busca;
  - [x] Pegar prefixo do Google Trends;
  - [ ] Iniciar robô de texto;
  - [ ] Iniciar robô de imagens;
  - [ ] Iniciar robô de vídeo;
  - [ ] Iniciar robô de Youtube.
---
- [ ] **Robô de texto**
  - [ ] Estrutura de dados;
  - [ ] Verificar língua;
  - [ ] Traduzir para o inglês;
  - [ ] Pegar conteúdo do Wikipédia;
  - [ ] Limpar o conteúdo;
  - [ ] Quebrar em sentenças;
  - [ ] Pegar a interpretação do Watson;
  - [ ] Adicionar tags;
  - [ ] Traduzir para a língua de origem;
  - [ ] Salvar estrutura de dados.
---
- [ ] **Robô de imagens**
  - [ ] Carregar a estrutura de dados;
  - [ ] Buscar as imagens no Google Imagens;
  - [ ] Baixar as imagens;
  - [ ] Salvar a estrutura de dados.
---
- [ ] **Robô do Youtube**
  - [ ] Autenticar com o OAuth;
  - [ ] Upload do vídeo;
  - [ ] Upload do thumbnail.
